Use tabs for indentation rather than spaces
The git CodingGuidelines state that tabs are preferred.

Signed-off-by: Tim Henigan <tim.henigan@gmail.com>

diff --git a/git-diffall b/git-diffall
--- a/git-diffall
+++ b/git-diffall
@@ -35,8 +35,8 @@ TOOL_MODE=diff
 merge_tool="$(get_merge_tool)"
 if test -z "$merge_tool"
 then
-    echo "Error: Either the 'diff.tool' or 'merge.tool' option must be set."
-    usage
+	echo "Error: Either the 'diff.tool' or 'merge.tool' option must be set."
+	usage
 fi
 
 start_dir=$(pwd)
@@ -44,17 +44,17 @@ start_dir=$(pwd)
 # needed to access tar utility
 cdup=$(git rev-parse --show-cdup) &&
 cd "$cdup" || {
-    echo >&2 "Cannot chdir to $cdup, the toplevel of the working tree"
-    exit 1
+	echo >&2 "Cannot chdir to $cdup, the toplevel of the working tree"
+	exit 1
 }
 
 # mktemp is not available on all platforms (missing from msysgit)
 # Use a hard-coded tmp dir if it is not available
 if test -z $(which mktemp 2>/dev/null)
 then
-    tmp=/tmp/git-diffall-tmp
+	tmp=/tmp/git-diffall-tmp
 else
-    tmp="$(mktemp -d -t tmp.XXXXXX)"
+	tmp="$(mktemp -d -t tmp.XXXXXX)"
 fi
 mkdir -p "$tmp"
 
@@ -71,120 +71,120 @@ copy_back=
 
 while test $# != 0
 do
-    case "$1" in
-    -h|--h|--he|--hel|--help)
-        usage
-        ;;
-    --cached)
-        compare_staged=1
-        ;;
-    --copy-back)
-        copy_back=1
-        ;;
-    -x|--e|--ex|--ext|--extc|--extcm|--extcmd)
-        diff_tool=$2
-        shift
-        echo "$diff_tool"
-        ;;
-    --)
-        path_sep=1
-        ;;
-    -*)
-        echo Invalid option: "$1"
-        usage
-        ;;
-    *)
-        # could be commit, commit range or path limiter
-        case "$1" in
-        *...*)
-            left=${1%...*}
-            right=${1#*...}
-            common_ancestor=1
-            ;;
-        *..*)
-            left=${1%..*}
-            right=${1#*..}
-            ;;
-        *)
-            if test -n "$path_sep"
-            then
-                if test -z "$paths"
-                then
-                    paths=$1
-                else
-                    paths="$paths $1"
-                fi
-            elif test -z "$left"
-            then
-                left=$1
-            elif test -z "$right"
-            then
-                right=$1
-            else
-                if test -z "$paths"
-                then
-                    paths=$1
-                else
-                    paths="$paths $1"
-                fi
-            fi
-            ;;
-        esac
-        ;;
-    esac
-    shift
+	case "$1" in
+	-h|--h|--he|--hel|--help)
+		usage
+		;;
+	--cached)
+		compare_staged=1
+		;;
+	--copy-back)
+		copy_back=1
+		;;
+	-x|--e|--ex|--ext|--extc|--extcm|--extcmd)
+		diff_tool=$2
+		shift
+		echo "$diff_tool"
+		;;
+	--)
+		path_sep=1
+		;;
+	-*)
+		echo Invalid option: "$1"
+		usage
+		;;
+	*)
+		# could be commit, commit range or path limiter
+		case "$1" in
+		*...*)
+			left=${1%...*}
+			right=${1#*...}
+			common_ancestor=1
+			;;
+		*..*)
+			left=${1%..*}
+			right=${1#*..}
+			;;
+		*)
+			if test -n "$path_sep"
+			then
+				if test -z "$paths"
+				then
+					paths=$1
+				else
+					paths="$paths $1"
+				fi
+			elif test -z "$left"
+			then
+				left=$1
+			elif test -z "$right"
+			then
+				right=$1
+			else
+				if test -z "$paths"
+				then
+					paths=$1
+				else
+					paths="$paths $1"
+				fi
+			fi
+			;;
+		esac
+		;;
+	esac
+	shift
 done
 
 # Determine the set of files which changed
 if test -n "$left" && test -n "$right"
 then
-    left_dir="cmt-$(git rev-parse --short $left)"
-    right_dir="cmt-$(git rev-parse --short $right)"
+	left_dir="cmt-$(git rev-parse --short $left)"
+	right_dir="cmt-$(git rev-parse --short $right)"
 
-    if test -n "$compare_staged"
-    then
-        usage
-    elif test -n "$common_ancestor"
-    then
-        git diff --name-only "$left"..."$right" -- $paths > "$tmp"/filelist
-    else
-        git diff --name-only "$left" "$right" -- $paths > "$tmp"/filelist
-    fi
+	if test -n "$compare_staged"
+	then
+		usage
+	elif test -n "$common_ancestor"
+	then
+		git diff --name-only "$left"..."$right" -- $paths > "$tmp"/filelist
+	else
+		git diff --name-only "$left" "$right" -- $paths > "$tmp"/filelist
+	fi
 elif test -n "$left"
 then
-    left_dir="cmt-$(git rev-parse --short $left)"
+	left_dir="cmt-$(git rev-parse --short $left)"
 
-    if test -n "$compare_staged"
-    then
-        right_dir="staged"
-        git diff --name-only --cached "$left" -- $paths > "$tmp"/filelist
-    else
-        right_dir="working_tree"
-        git diff --name-only "$left" -- $paths > "$tmp"/filelist
-    fi
+	if test -n "$compare_staged"
+	then
+		right_dir="staged"
+		git diff --name-only --cached "$left" -- $paths > "$tmp"/filelist
+	else
+		right_dir="working_tree"
+		git diff --name-only "$left" -- $paths > "$tmp"/filelist
+	fi
 else
-    left_dir="HEAD"
+	left_dir="HEAD"
 
-    if test -n "$compare_staged"
-    then
-        right_dir="staged"
-        git diff --name-only --cached -- $paths > "$tmp"/filelist
-    else
-        right_dir="working_tree"
-        git diff --name-only -- $paths > "$tmp"/filelist
-    fi
+	if test -n "$compare_staged"
+	then
+		right_dir="staged"
+		git diff --name-only --cached -- $paths > "$tmp"/filelist
+	else
+		right_dir="working_tree"
+		git diff --name-only -- $paths > "$tmp"/filelist
+	fi
 fi
 
 # Exit immediately if there are no diffs
 if test ! -s "$tmp"/filelist
 then
-    exit 0
+	exit 0
 fi
 
 if test -n "$copy_back" && test "$right_dir" != "working_tree"
 then
-    echo "--copy-back is only valid when diff includes the working tree."
-    exit 1
+	echo "--copy-back is only valid when diff includes the working tree."
+	exit 1
 fi
 
 # Create the named tmp directories that will hold the files to be compared
@@ -193,60 +193,60 @@ mkdir -p "$tmp"/"$left_dir" "$tmp"/"$right_dir"
 # Populate the tmp/right_dir directory with the files to be compared
 if test -n "$right"
 then
-    while read name
-    do
-        ls_list=$(git ls-tree $right $name)
-        if test -n "$ls_list"
-    then
-            mkdir -p "$tmp"/"$right_dir"/"$(dirname "$name")"
-            git show "$right":"$name" > "$tmp"/"$right_dir"/"$name" || true
-        fi
-    done < "$tmp"/filelist
+	while read name
+	do
+		ls_list=$(git ls-tree $right $name)
+		if test -n "$ls_list"
+	then
+			mkdir -p "$tmp"/"$right_dir"/"$(dirname "$name")"
+			git show "$right":"$name" > "$tmp"/"$right_dir"/"$name" || true
+		fi
+	done < "$tmp"/filelist
 elif test -n "$compare_staged"
 then
-    while read name
-    do
-        ls_list=$(git ls-files -- $name)
-        if test -n "$ls_list"
-    then
-            mkdir -p "$tmp"/"$right_dir"/"$(dirname "$name")"
-            git show :"$name" > "$tmp"/"$right_dir"/"$name"
-        fi
-    done < "$tmp"/filelist
+	while read name
+	do
+		ls_list=$(git ls-files -- $name)
+		if test -n "$ls_list"
+	then
+			mkdir -p "$tmp"/"$right_dir"/"$(dirname "$name")"
+			git show :"$name" > "$tmp"/"$right_dir"/"$name"
+		fi
+	done < "$tmp"/filelist
 else
-    if test -n "$(which gnutar 2>/dev/null)"
-    then
-        gnutar --ignore-failed-read -c -T "$tmp"/filelist | (cd "$tmp"/"$right_dir" && gnutar -x)
-    else
-        tar --ignore-failed-read -c -T "$tmp"/filelist | (cd "$tmp"/"$right_dir" && tar -x)
-    fi
+	if test -n "$(which gnutar 2>/dev/null)"
+	then
+		gnutar --ignore-failed-read -c -T "$tmp"/filelist | (cd "$tmp"/"$right_dir" && gnutar -x)
+	else
+		tar --ignore-failed-read -c -T "$tmp"/filelist | (cd "$tmp"/"$right_dir" && tar -x)
+	fi
 fi
 
 # Populate the tmp/left_dir directory with the files to be compared
 while read name
 do
-    if test -n "$left"
-    then
-        ls_list=$(git ls-tree $left $name)
-        if test -n "$ls_list"
-        then
-            mkdir -p "$tmp"/"$left_dir"/"$(dirname "$name")"
-            git show "$left":"$name" > "$tmp"/"$left_dir"/"$name" || true
-        fi
-    else
-        if test -n "$compare_staged"
-        then
-            ls_list=$(git ls-tree HEAD $name)
-            if test -n "$ls_list"
-            then
-                mkdir -p "$tmp"/"$left_dir"/"$(dirname "$name")"
-                git show HEAD:"$name" > "$tmp"/"$left_dir"/"$name"
-                fi
-            else
-                mkdir -p "$tmp"/"$left_dir"/"$(dirname "$name")"
-                git show :"$name" > "$tmp"/"$left_dir"/"$name"
-        fi
-    fi
+	if test -n "$left"
+	then
+		ls_list=$(git ls-tree $left $name)
+		if test -n "$ls_list"
+		then
+			mkdir -p "$tmp"/"$left_dir"/"$(dirname "$name")"
+			git show "$left":"$name" > "$tmp"/"$left_dir"/"$name" || true
+		fi
+	else
+		if test -n "$compare_staged"
+		then
+			ls_list=$(git ls-tree HEAD $name)
+			if test -n "$ls_list"
+			then
+				mkdir -p "$tmp"/"$left_dir"/"$(dirname "$name")"
+				git show HEAD:"$name" > "$tmp"/"$left_dir"/"$name"
+				fi
+			else
+				mkdir -p "$tmp"/"$left_dir"/"$(dirname "$name")"
+				git show :"$name" > "$tmp"/"$left_dir"/"$name"
+		fi
+	fi
 done < "$tmp"/filelist
 
 cd "$tmp"
@@ -255,27 +255,27 @@ REMOTE="$right_dir"
 
 if test -n "$diff_tool"
 then
-    export BASE
-    eval $diff_tool '"$LOCAL"' '"$REMOTE"'
+	export BASE
+	eval $diff_tool '"$LOCAL"' '"$REMOTE"'
 else
-    run_merge_tool "$merge_tool" false
+	run_merge_tool "$merge_tool" false
 fi
 
 # This function is called on exit
 cleanup () {
-    cd "$start_dir"
+	cd "$start_dir"
 
-    # Copy files back to the working dir, if requested
-    if test -n "$copy_back" && test "$right_dir" = "working_tree"
-    then
-        git_top_dir=$(git rev-parse --show-toplevel)
-        find "$tmp/$right_dir" -type f|while read file; do
-            cp "$file" "$git_top_dir/${file#$tmp/$right_dir/}"
-        done
-    fi
+	# Copy files back to the working dir, if requested
+	if test -n "$copy_back" && test "$right_dir" = "working_tree"
+	then
+		git_top_dir=$(git rev-parse --show-toplevel)
+		find "$tmp/$right_dir" -type f|while read file; do
+			cp "$file" "$git_top_dir/${file#$tmp/$right_dir/}"
+		done
+	fi
 
-    # Remove the tmp directory
-    rm -rf "$tmp"
+	# Remove the tmp directory
+	rm -rf "$tmp"
 }
 
 trap cleanup EXIT
